# Generated by Django 3.0 on 2021-04-30 00:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0007_datavencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primeiro nome')),
                ('sobrenome_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cep_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('rua_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('bairro_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('numero_endereco_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº.')),
                ('complemento_endereco_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('telefone_cliente', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone Celular')),
                ('email_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('instalando', models.BooleanField(default=False, verbose_name='Status Instalado')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data da Instalação')),
                ('hora_instalacao', models.TimeField(blank=True, null=True, verbose_name='Hora da Instalação')),
                ('observacao_instalacao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.Cidade', verbose_name='Cidade')),
                ('data_vencimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.DataVencimento', verbose_name='Data de Vencimento')),
                ('planos_instalacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.PlanosInternet', verbose_name='Planos Instalação')),
            ],
            options={
                'verbose_name_plural': 'Instalação',
            },
        ),
    ]
