# Generated by Django 3.0 on 2021-04-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_cidade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cidade',
            },
        ),
        migrations.CreateModel(
            name='PlanosInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Planos Internet',
            },
        ),
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True)),
                ('rg_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('rua_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_endereco_cliente', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('cidade_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_cliente', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('email_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('plano_instalacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.PlanosInternet')),
            ],
            options={
                'verbose_name_plural': 'Instalação',
            },
        ),
    ]
