# Generated by Django 3.0 on 2021-04-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_delete_instalacao'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='plano_instalacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.PlanosInternet'),
        ),
        migrations.DeleteModel(
            name='PlanosInternet',
        ),
    ]
