# Generated by Django 3.0 on 2021-04-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
