# Generated by Django 3.0 on 2021-04-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210426_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacao',
            name='plano_instalacao',
        ),
    ]
