# Generated by Django 3.0 on 2021-04-27 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_delete_instalacao'),
        ('sales', '0003_remove_instalacao_plano_instalacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='plano_instalacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='components.PlanosInternet'),
            preserve_default=False,
        ),
    ]
