# Generated by Django 3.0 on 2021-04-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_instalacao_plano_instalacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacao',
            name='plano_instalacao',
        ),
    ]
