# Generated by Django 3.0 on 2021-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210505_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='material_utilizado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
