# Generated by Django 3.0 on 2021-04-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_instalacao_plano_instalacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='numero_endereco_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
