# Generated by Django 3.0 on 2021-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_instalacao_material_utilizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='material_utilizado',
            field=models.TextField(blank=True, null=True, verbose_name='Material utilizado'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='observacao_instalacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
