# Generated by Django 3.0 on 2021-05-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210507_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacao',
            name='rg_cliente',
        ),
    ]
