# Generated by Django 3.0 on 2021-04-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_delete_instalacao'),
        ('sales', '0006_auto_20210426_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='planos_instalacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='components.PlanosInternet'),
            preserve_default=False,
        ),
    ]
