# Generated by Django 3.0 on 2021-04-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_instalacao_planos_instalacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='sobrenome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
