# Generated by Django 3.0 on 2021-05-08 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_instalacao_rg_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='data_instalacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
