# Generated by Django 3.0 on 2021-04-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_delete_instalacao'),
        ('sales', '0008_instalacao_sobrenome_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='components.Cidade'),
            preserve_default=False,
        ),
    ]
