# Generated by Django 3.0 on 2021-04-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_instalacao_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacao',
            name='cidade_cliente',
        ),
        migrations.RemoveField(
            model_name='instalacao',
            name='uf_cliente',
        ),
    ]
