# Generated by Django 3.0 on 2021-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210427_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='cep_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
