# Generated by Django 3.0 on 2021-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_instalacao_data_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='boleto_entregue',
            field=models.BooleanField(default=False),
        ),
    ]
