# Generated by Django 3.0 on 2021-04-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_instalacao_cep_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='complemento_endereco_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
