# Generated by Django 3.0 on 2021-04-27 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_instalacao_complemento_endereco_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
