# Generated by Django 3.0 on 2021-04-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_instalacao_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='instalando',
            field=models.BooleanField(default=False),
        ),
    ]
