# Generated by Django 3.0 on 2021-05-14 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0013_auto_20210512_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='funcionario_instalacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
