# Generated by Django 3.0 on 2021-04-30 00:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_instalacao_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='hora_instalacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='instalando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='observacao_instalacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
