# Generated by Django 3.0 on 2021-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_instalacao_funcionario_instalacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='data_concluido',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Conclusão'),
        ),
    ]
