# Generated by Django 3.0 on 2021-04-30 00:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_datavencimento'),
        ('sales', '0014_auto_20210429_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacao',
            name='concluido',
        ),
        migrations.AddField(
            model_name='instalacao',
            name='concluido_instalacao',
            field=models.BooleanField(default=False, verbose_name='Status Concluído'),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='data_vencimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='components.DataVencimento', verbose_name='Data de Vencimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='bairro_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='cep_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.Cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='complemento_endereco_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Instalação'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='email_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='hora_instalacao',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora da Instalação'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='instalando',
            field=models.BooleanField(default=False, verbose_name='Status Instalado'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='numero_endereco_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº.'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='observacao_instalacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='planos_instalacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.PlanosInternet', verbose_name='Planos Instalação'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='rg_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='rua_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='sobrenome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='telefone_cliente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone Celular'),
        ),
    ]
