# Generated by Django 3.0 on 2021-04-29 03:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20210427_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='hora_instalacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='observacao_instalacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
