# Generated by Django 3.0 on 2021-04-30 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_datavencimento'),
        ('sales', '0014_auto_20210429_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='data_vencimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='components.DataVencimento'),
            preserve_default=False,
        ),
    ]
