# Generated by Django 3.0 on 2021-04-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20210429_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacao',
            name='concluido_instalacao',
        ),
    ]
