# Generated by Django 3.0 on 2021-04-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_instalacao_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cliente'),
        ),
    ]
