# Generated by Django 3.0 on 2021-04-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20210429_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='data_instalacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
