# Generated by Django 3.0 on 2021-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20210515_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Finalização'),
        ),
    ]
