# Generated by Django 3.0 on 2021-04-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_datavencimento'),
        ('sales', '0017_auto_20210429_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='data_vencimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.DataVencimento', verbose_name='Data de Vencimento'),
        ),
    ]
