# Generated by Django 3.0 on 2021-04-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20210429_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacao',
            old_name='concluido',
            new_name='concluido_instalacao',
        ),
    ]
