# Generated by Django 3.0 on 2021-05-27 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0018_instalacao_data_finalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='instalacao_criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instalacao_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='instalacao_finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instalacao_finalizado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
