# Generated by Django 3.0 on 2021-06-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_vendedores'),
        ('sales', '0020_instalacao_instalacao_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='instalacao_vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='components.Vendedores', verbose_name='Vendedores'),
            preserve_default=False,
        ),
    ]
