# Generated by Django 3.0 on 2021-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20210609_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='telefone1_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='telefone2_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
    ]
