# Generated by Django 3.0 on 2021-07-29 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_funcionariosparavale'),
        ('sales', '0023_clientesvoip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeRefeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_vale', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vale', models.DateField(blank=True, null=True)),
                ('nome_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='components.FuncionariosParaVale')),
            ],
            options={
                'verbose_name_plural': ' Vale Refeição',
            },
        ),
    ]
