# Generated by Django 3.0 on 2021-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_valerefeicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='valerefeicao',
            name='funcionario',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
