# Generated by Django 3.0 on 2021-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_valerefeicao_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valerefeicao',
            name='funcionario',
        ),
        migrations.AlterField(
            model_name='valerefeicao',
            name='nome_funcionario',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
