# Generated by Django 3.0 on 2021-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_auto_20210730_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='valerefeicao',
            name='status_pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
