# Generated by Django 3.0 on 2021-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_valerefeicao_status_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF'),
        ),
    ]
