# Generated by Django 3.0 on 2021-10-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_cancelamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelamentos',
            name='data',
        ),
    ]
