# Generated by Django 3.0 on 2021-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_remove_cancelamentos_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelamentos',
            name='Endereco',
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='Numero',
            field=models.CharField(default=1, max_length=255, verbose_name='Número do Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='bairro',
            field=models.CharField(default=1, max_length=255, verbose_name='Bairro do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='cep',
            field=models.CharField(default=1, max_length=255, verbose_name='CEP do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='logradouro',
            field=models.CharField(default=1, max_length=255, verbose_name='Rua do Cliente'),
            preserve_default=False,
        ),
    ]
