# Generated by Django 3.0 on 2021-10-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_auto_20211023_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelamentos',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='cancelamentos',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cancelamentos',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cancelamentos',
            name='logradouro',
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='Endereco',
            field=models.CharField(default=1, max_length=255, verbose_name='Endereço do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do serviço'),
        ),
    ]
