# Generated by Django 3.0 on 2021-10-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_auto_20211023_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelamentos',
            name='bairro',
            field=models.CharField(default=1, max_length=255, verbose_name='Bairro do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='cep',
            field=models.CharField(default=1, max_length=255, verbose_name='CEP do Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancelamentos',
            name='numero',
            field=models.CharField(default=1, max_length=255, verbose_name='Número do Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancelamentos',
            name='Endereco',
            field=models.CharField(max_length=255, verbose_name='Rua do Cliente'),
        ),
    ]
