# Generated by Django 3.0 on 2021-10-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_auto_20211023_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelamentos',
            old_name='Endereco',
            new_name='endereco',
        ),
    ]
