# Generated by Django 3.0 on 2021-10-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_auto_20211023_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelamentos',
            name='plano_internet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
