# Generated by Django 3.0 on 2021-10-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_auto_20211023_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelamentos',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
