# Generated by Django 3.0 on 2021-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_instalacao_como_conheceu_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='data_nascimento_cliente',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='instalacao',
            name='rg_cliente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
    ]
