# Generated by Django 3.0 on 2021-08-25 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.TextField(verbose_name='Nome da Tarefa')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('analisando', models.BooleanField(default=False)),
                ('previsao_conclusao', models.DateField(blank=True, null=True, verbose_name='Previsao de Conclusão')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data da  Conclusão')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
