# Generated by Django 3.0 on 2021-05-05 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=255, verbose_name='Categoria do serviço')),
            ],
            options={
                'verbose_name_plural': 'Categoria dos serviços',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_servico', models.TextField(blank=True, null=True, verbose_name='Endereço do serviço')),
                ('servico_para_executar', models.TextField(blank=True, null=True, verbose_name='Serviço a fazer')),
                ('servico_executado', models.TextField(blank=True, null=True, verbose_name='Serviço executado')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação')),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Data agendada')),
                ('hora_agendada', models.TimeField(blank=True, null=True, verbose_name='hora agendada')),
                ('status_agendado', models.BooleanField(default=False, verbose_name='Agendado')),
                ('material_utilizado', models.TextField(blank=True, null=True, verbose_name='Material utilizado')),
                ('status_concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_finalizacao', models.DateField(blank=True, null=True, verbose_name='Data da conclusão')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.CategoriaServico', verbose_name='Categoria do serviço')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
