# Generated by Django 3.0 on 2021-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='nome_clinte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do cliente'),
        ),
    ]
