# Generated by Django 3.0 on 2021-05-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servico_nome_clinte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome_clinte',
            new_name='nome_cliente',
        ),
    ]
