# Generated by Django 3.0 on 2021-05-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210507_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome_cliente',
            new_name='contato_servico',
        ),
    ]
