# Generated by Django 3.0 on 2021-05-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servico_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='funcionario',
        ),
    ]
