# Generated by Django 3.0 on 2021-05-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servico_funcionario_instalacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='funcionario_instalacao',
            new_name='funcionario_servico',
        ),
    ]
