# Generated by Django 3.0 on 2021-05-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_auto_20210520_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='criado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
