# Generated by Django 3.0 on 2021-06-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicovoip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicovoip',
            options={'verbose_name_plural': 'Serviço Voip'},
        ),
    ]
