# Generated by Django 3.0 on 2021-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20210531_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicovoip',
            old_name='Senha_voip',
            new_name='senha_voip',
        ),
        migrations.AddField(
            model_name='servicovoip',
            name='numero_telefone_voip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone Voip'),
        ),
    ]
