# Generated by Django 3.0 on 2021-06-03 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0013_auto_20210602_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='agendado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agendado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
