# Generated by Django 3.0 on 2021-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servico_agendado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicovoip',
            name='portabilidade_voip',
            field=models.BooleanField(default=False, verbose_name='Portabilidade'),
        ),
    ]
