# Generated by Django 3.0 on 2021-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicovoip_portabilidade_voip'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicovoip',
            name='boleto_entregue',
            field=models.BooleanField(default=False),
        ),
    ]
