# Generated by Django 3.0 on 2021-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_servicovoip_boleto_entregue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Tipo de Servico',
                'verbose_name_plural': 'Tipos de Serviços',
            },
        ),
    ]
