# Generated by Django 3.0 on 2021-11-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_tiposservico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposServico',
            new_name='TipoServico',
        ),
    ]
