# Generated by Django 3.0 on 2021-11-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20211103_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoServico',
            new_name='TipoDeServico',
        ),
        migrations.AlterModelOptions(
            name='tipodeservico',
            options={'verbose_name_plural': 'Tipos de Serviços'},
        ),
    ]
