# Generated by Django 3.0 on 2021-11-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20211103_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.TipoDeServico'),
        ),
    ]
