# Generated by Django 3.0 on 2021-11-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_servico_tipo_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='tipo_servico',
            new_name='tipo_de_servico',
        ),
    ]
