# Generated by Django 3.0 on 2021-11-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20211103_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tipo_de_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_de_servico', to='services.TipoDeServico'),
        ),
    ]
