# Generated by Django 3.0 on 2021-11-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20211103_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='tipo_de_servico',
        ),
    ]
