# Generated by Django 3.0 on 2021-12-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20211212_2157'),
        ('services', '0023_remove_servico_tipo_de_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='plano_internet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='components.PlanosInternet', verbose_name='Plano Instalado'),
        ),
    ]
