# Generated by Django 3.0 on 2022-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_servico_plano_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='status_analise',
            field=models.BooleanField(default=False, verbose_name='Em Análise'),
        ),
    ]
