# Generated by Django 3.0 on 2022-03-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_servico_status_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
