# Generated by Django 3.0 on 2021-05-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Entrada de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_produto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Produto')),
            ],
            options={
                'verbose_name_plural': 'Saída de Produtos',
            },
        ),
        migrations.CreateModel(
            name='TotalProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.EntradaProduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Produto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.SaidaProduto')),
            ],
            options={
                'verbose_name_plural': 'Total de Produtos',
            },
        ),
        migrations.AddField(
            model_name='entradaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Produto'),
        ),
    ]
