# Generated by Django 3.0 on 2021-04-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_entradaproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=10, max_digits=10)),
                ('entrada_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Produto')),
            ],
            options={
                'verbose_name_plural': 'Saída de Produtos',
            },
        ),
    ]
