# Generated by Django 3.0 on 2021-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_saidaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saidaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
