# Generated by Django 3.0 on 2021-04-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210427_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaproduto',
            old_name='entrada_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='saidaproduto',
            old_name='entrada_produto',
            new_name='produto',
        ),
    ]
