# Generated by Django 3.0 on 2021-04-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210427_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.EntradaProduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Produto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.SaidaProduto')),
            ],
            options={
                'verbose_name_plural': 'Total de Produtos',
            },
        ),
    ]
