# Generated by Django 3.0 on 2021-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicovoip',
            name='portabilidade_analise',
            field=models.BooleanField(default=False, verbose_name='Portabilidade em Análise'),
        ),
    ]
