# Generated by Django 3.0 on 2021-05-05 15:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_manual', models.CharField(max_length=255)),
                ('texto_manual', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Manuais',
            },
        ),
    ]
