# Generated by Django 3.0 on 2021-05-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20210508_1936'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhasEquipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.FabricanteEquipamentos')),
            ],
            options={
                'verbose_name_plural': 'Manuais',
            },
        ),
    ]
