# Generated by Django 3.0 on 2021-05-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_senhasequipamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senhasequipamentos',
            options={'verbose_name_plural': 'Senhas Equipamentos'},
        ),
    ]
