# Generated by Django 3.0 on 2021-05-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210509_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhasequipamentos',
            name='ip_equipamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
