# Generated by Django 3.0 on 2021-05-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20210511_1359'),
        ('core', '0004_senhasequipamentos_ip_equipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhasPorEquipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.ModelosEquipamentos')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='components.FabricanteEquipamentos')),
            ],
            options={
                'verbose_name_plural': 'Senhas por Equipamentos',
            },
        ),
    ]
