# Generated by Django 3.0 on 2021-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_senhasporequipamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhasporequipamentos',
            name='codigo_equipamento',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
