# Generated by Django 3.0 on 2021-05-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_senhasporequipamentos_codigo_equipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminaisOpticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cto', models.CharField(blank=True, max_length=50, null=True)),
                ('rua_cto', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_rua_cto', models.CharField(max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('pon_cto', models.CharField(max_length=100)),
                ('conexoes_opticas_cto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quant_conexoes_usadas_cto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao_cto', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CTO´s',
            },
        ),
    ]
