# Generated by Django 3.0 on 2021-05-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_terminaisopticos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminaisopticos',
            name='conexoes_opticas_cto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='terminaisopticos',
            name='numero_rua_cto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='terminaisopticos',
            name='pon_cto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terminaisopticos',
            name='quant_conexoes_usadas_cto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
