# Generated by Django 3.0 on 2021-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210513_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminaisopticos',
            name='quant_conexoes_usadas_cto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
