# Generated by Django 3.0 on 2021-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210513_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminaisopticos',
            name='conexoes_opticas_cto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
