# Generated by Django 3.0 on 2021-05-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210513_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerminaisOpticos',
        ),
    ]
