# Generated by Django 3.0 on 2021-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_terminaisopticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhasporequipamentos',
            name='sn_equipamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
