# Generated by Django 3.0 on 2021-05-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_servico_funcionario'),
        ('sales', '0018_instalacao_data_finalizacao'),
        ('core', '0012_senhasporequipamentos_sn_equipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerarResultadosDiarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_instalacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.Instalacao')),
                ('quantidade_servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.Servico')),
            ],
            options={
                'verbose_name_plural': 'Gerar Resultados Diários',
            },
        ),
    ]
