# Generated by Django 3.0 on 2021-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gerarresultadosdiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhasporequipamentos',
            name='patrimonio_equipamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
