# Generated by Django 3.0 on 2021-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_senhasporequipamentos_patrimonio_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senhasporequipamentos',
            name='patrimonio_equipamento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
