# Generated by Django 3.0 on 2021-08-02 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210608_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='senhasporequipamentos',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
