# Generated by Django 3.0 on 2021-12-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_senhasporequipamentos_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senhasporequipamentos',
            name='codigo_equipamento',
            field=models.CharField(max_length=120, verbose_name='Código do equipamento'),
        ),
    ]
