# Generated by Django 3.0 on 2022-06-01 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vendas_produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Total')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True, verbose_name='Última alteração')),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='concluido_por', to=settings.AUTH_USER_MODEL)),
                ('criador_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='criador_por', to=settings.AUTH_USER_MODEL)),
                ('ultima_alteracao_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ultima_alteracao_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda de Produto',
                'verbose_name_plural': 'Vendas de Produtos',
            },
        ),
    ]
