# Generated by Django 3.0 on 2022-06-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas_produtos',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='vendas_produtos',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Unitário'),
        ),
    ]
