# Generated by Django 3.0 on 2022-06-01 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20220601_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas_produtos',
            name='data_conluido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas_produtos',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
