# Generated by Django 3.0 on 2022-06-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20220601_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas_produtos',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
    ]
