# Generated by Django 3.0 on 2022-06-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20220601_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendasprodutos',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
