# Generated by Django 3.0 on 2022-06-01 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_vendasprodutos_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendasprodutos',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
