# Generated by Django 3.0 on 2022-06-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20220601_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendasprodutos',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
