# Generated by Django 3.0 on 2022-06-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20220607_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasprodutos',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
    ]
