# Generated by Django 3.0 on 2021-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionarQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Adicionar Quantidade',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_cidade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cidade',
            },
        ),
        migrations.CreateModel(
            name='DataVencimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Datas Venciemento',
            },
        ),
        migrations.CreateModel(
            name='PlanosInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Planos Internet',
            },
        ),
    ]
