# Generated by Django 3.0 on 2021-04-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cfp_cliente', models.CharField(blank=True, max_length=14, null=True)),
                ('rg_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('rua_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_endereco_cliente', models.DecimalField(decimal_places=10, max_digits=10)),
                ('cidade_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_cliente', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('email_cliente', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanosInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=30)),
            ],
        ),
    ]
