# Generated by Django 3.0 on 2021-04-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacao',
            options={'verbose_name_plural': 'Instalação'},
        ),
        migrations.AlterModelOptions(
            name='planosinternet',
            options={'verbose_name_plural': 'Planos Internet'},
        ),
        migrations.AddField(
            model_name='instalacao',
            name='plano_instalacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='components.PlanosInternet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instalacao',
            name='numero_endereco_cliente',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
