# Generated by Django 3.0 on 2021-05-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacricanteEquipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fabricante', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Fabricante equipamentos',
            },
        ),
    ]
