# Generated by Django 3.0 on 2021-04-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20210426_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacao',
            old_name='cfp_cliente',
            new_name='cpf_cliente',
        ),
    ]
