# Generated by Django 3.0 on 2021-05-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_facricanteequipamentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacricanteEquipamentos',
            new_name='FabricanteEquipamentos',
        ),
    ]
