# Generated by Django 3.0 on 2021-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20210508_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelosEquipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Modelosequipamentos',
            },
        ),
    ]
