# Generated by Django 3.0 on 2021-05-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_modelosequipamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelosequipamentos',
            options={'verbose_name_plural': 'Modelos equipamentos'},
        ),
    ]
