# Generated by Django 3.0 on 2021-04-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_cidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instalacao',
        ),
    ]
