# Generated by Django 3.0 on 2021-04-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_delete_instalacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionarQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Adicionar Quantidade',
            },
        ),
    ]
