# Generated by Django 3.0 on 2021-04-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_adicionarquantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVencimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Datas Venciemento',
            },
        ),
    ]
