# Generated by Django 3.0 on 2021-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('numero_baixo', models.CharField(max_length=20)),
                ('numero_alto', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Ruas',
            },
        ),
    ]
