# Generated by Django 3.0 on 2021-07-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_ruas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionariosParaVale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Funcionarios Para Vale',
            },
        ),
    ]
