# Generated by Django 3.0 on 2022-04-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_ruas_bairro_ruas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruas',
            name='cep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ruas',
            name='numero_alto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ruas',
            name='numero_baixo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
