# Generated by Django 3.0 on 2021-05-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categoria de Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='OrigemValores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_valor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Origem do valor',
            },
        ),
        migrations.CreateModel(
            name='TipoCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_custo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipo de custo',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_pagamento', models.CharField(max_length=255)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('data_pagamento', models.DateField()),
                ('observacao_pagamento', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.CategoriaPagamento')),
                ('origem_valor_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.OrigemValores')),
                ('tipo_custo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.TipoCusto')),
            ],
            options={
                'verbose_name_plural': 'Pagamento',
            },
        ),
    ]
