# Generated by Django 3.0 on 2021-05-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemValores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_valor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Origem do valor',
            },
        ),
        migrations.CreateModel(
            name='TipoCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_custo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipo de custo',
            },
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_lancamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='nome_pagamento',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='motivo_pagamento',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='origem_valor_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.OrigemValores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo_custo_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.TipoCusto'),
            preserve_default=False,
        ),
    ]
