# Generated by Django 3.0 on 2021-04-28 11:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pagamento', models.CharField(max_length=255)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('data_pagamento', models.DateTimeField()),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_pagamento', ckeditor.fields.RichTextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.CategoriaPagamento')),
            ],
            options={
                'verbose_name_plural': 'Pagamento',
            },
        ),
    ]
