# Generated by Django 3.0 on 2021-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_agendapagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendapagamento',
            name='valor_pagamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
