# Generated by Django 3.0 on 2021-05-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_agendapagamento_valor_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendapagamento',
            name='status_pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
