# Generated by Django 3.0 on 2021-09-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_pagamento_status_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoEntradasSaidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluxo_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fluxo_saida', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fluxo_data', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fluxo Entradas e Saídas',
            },
        ),
    ]
