# Generated by Django 3.0 on 2021-09-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_fluxoentradassaidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxoentradassaidas',
            old_name='fluxo_entrada',
            new_name='SaidaDia',
        ),
        migrations.RenameField(
            model_name='fluxoentradassaidas',
            old_name='fluxo_saida',
            new_name='entradaDia',
        ),
        migrations.AddField(
            model_name='fluxoentradassaidas',
            name='banco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.OrigemValores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluxoentradassaidas',
            name='saldoInicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
