# Generated by Django 3.0 on 2021-11-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_formasdeentregaboletos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaboletos',
            name='forma_entrega_boleto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.FormasDeEntregaBoletos'),
        ),
    ]
