# Generated by Django 3.0 on 2021-11-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20211109_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDeBoletos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entrega de boletos ',
            },
        ),
        migrations.AlterField(
            model_name='entregaboletos',
            name='forma_entrega_boleto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.FormasEntregaBoletos'),
        ),
    ]
