# Generated by Django 3.0 on 2021-11-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20211110_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregadeboletos',
            name='forma_entrega_boleto',
        ),
    ]
