# Generated by Django 3.0 on 2021-11-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20211110_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntregaDeBoletos',
        ),
    ]
