# Generated by Django 3.0 on 2021-11-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_remove_entregadeboletos_forma_entrega_boleto'),
        ('payment', '0018_delete_entregadeboletos'),
    ]

    operations = [
    ]
