# Generated by Django 3.0 on 2021-11-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_merge_20211110_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormasDeEntregaBoletos',
        ),
    ]
