# Generated by Django 3.0 on 2021-11-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_entregadosboletos_formasdeentregadosboletos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregadosboletos',
            name='forma_entrega_boleto',
        ),
    ]
