# Generated by Django 3.0 on 2021-11-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_remove_entregadosboletos_forma_entrega_boleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaboletos',
            name='forma_entrega_boleto',
        ),
        migrations.DeleteModel(
            name='EntregaDosBoletos',
        ),
        migrations.DeleteModel(
            name='FormasDeEntregaDosBoletos',
        ),
        migrations.DeleteModel(
            name='EntregaBoletos',
        ),
        migrations.DeleteModel(
            name='FormasEntregaBoletos',
        ),
    ]
