# Generated by Django 3.0 on 2021-11-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_auto_20211110_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientesentregadosboletos',
            options={'verbose_name_plural': 'Boletos de clientes '},
        ),
    ]
