# Generated by Django 3.0 on 2021-11-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20211110_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesentregadosboletos',
            name='meio_entrega',
        ),
    ]
