# Generated by Django 3.0 on 2021-11-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_remove_clientesentregadosboletos_meio_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientesEntregaDosBoletos',
        ),
        migrations.DeleteModel(
            name='MeiosEntregaDosBoletos',
        ),
    ]
