# Generated by Django 3.0 on 2021-11-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_auto_20211110_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeiosEntregaBoletos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_entrega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meio de entrega')),
            ],
            options={
                'verbose_name_plural': 'Meio Entrega Boletos',
            },
        ),
    ]
