# Generated by Django 3.0 on 2021-11-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_clientesentregaboletos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesentregaboletos',
            name='forma_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.MeiosEntregaBoletos'),
        ),
    ]
