# Generated by Django 3.0 on 2021-11-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_auto_20211118_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesentregaboletos',
            name='boletos_assinados',
            field=models.BooleanField(default=False),
        ),
    ]
