# Generated by Django 3.0 on 2021-11-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_clientesentregaboletos_boletos_assinados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientesentregaboletos',
            old_name='boletos_assinados',
            new_name='boleto_assinado',
        ),
    ]
