# Generated by Django 3.0 on 2021-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_auto_20211128_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoEntradaSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_mes_atual', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('entrada_referente_mes_atual', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('data_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fluxo Entrada vs Saida',
            },
        ),
    ]
