# Generated by Django 3.0 on 2021-12-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_fluxoentradasaida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FluxoEntradaSaida',
            new_name='FluxoEntradaSaidaMensal',
        ),
    ]
