# Generated by Django 3.0 on 2022-01-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_auto_20211218_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoentradasaidamensal',
            name='custos_mensais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
