# Generated by Django 3.0 on 2022-02-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0037_fluxoentradasaidamensal_custos_mensais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='informacao_pagamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
