# Generated by Django 3.0 on 2022-03-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0038_pagamento_informacao_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesentregaboletos',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
