# Generated by Django 3.0 on 2022-03-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0039_auto_20220308_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapagamento',
            name='motivo_pagamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
