# Generated by Django 3.0 on 2022-03-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0040_auto_20220311_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxoentradasaidamensal',
            name='entrada_referente_mes_atual',
        ),
    ]
