# Generated by Django 3.0 on 2021-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminaisOpticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cto', models.CharField(blank=True, max_length=50, null=True)),
                ('rua_cto', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_rua_cto', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('pon_cto', models.CharField(blank=True, max_length=100, null=True)),
                ('conexoes_opticas_cto', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('quant_conexoes_usadas_cto', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('observacao_cto', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CTO´s',
            },
        ),
    ]
