# Generated by Django 3.0 on 2021-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminaisopticos',
            name='board_cto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
