# Generated by Django 3.0 on 2021-07-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0002_terminaisopticos_board_cto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixasEmenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caixa', models.CharField(blank=True, max_length=50, null=True)),
                ('rua_caixa_emenda', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_rua_cto', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Caixas de Emenda',
            },
        ),
    ]
