# Generated by Django 3.0 on 2021-07-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0003_caixasemenda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaixasEmenda',
            new_name='CaixasDeEmenda',
        ),
    ]
