# Generated by Django 3.0 on 2021-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0004_auto_20210712_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='PonPorCaixaEmenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_pon', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('pon_pon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pon por caixa',
            },
        ),
    ]
