# Generated by Django 3.0 on 2021-07-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0006_pon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pon',
            new_name='NumeroPon',
        ),
    ]
