# Generated by Django 3.0 on 2021-07-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0007_auto_20210712_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponporcaixaemenda',
            name='numero_pon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cto.NumeroPon'),
            preserve_default=False,
        ),
    ]
