# Generated by Django 3.0 on 2021-07-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0009_auto_20210712_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponporcaixaemenda',
            name='numero_pon',
        ),
        migrations.AddField(
            model_name='ponporcaixaemenda',
            name='caixa_pon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cto.CaixasDeEmenda'),
            preserve_default=False,
        ),
    ]
