# Generated by Django 3.0 on 2021-07-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0010_auto_20210712_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponporcaixaemenda',
            old_name='caixa_pon',
            new_name='caixa_emenda',
        ),
    ]
