# Generated by Django 3.0 on 2021-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0012_primarias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixasDasPrimarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('logradouro_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_caixa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Caixas das Primarias',
            },
        ),
    ]
