# Generated by Django 3.0 on 2021-07-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0013_caixasdasprimarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixasdasprimarias',
            name='primaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cto.Primarias'),
            preserve_default=False,
        ),
    ]
